# Here are the parts of the C AST that we want to represent.
DEF = 'DEF'
CALL = 'CALL'
ASSIGN = 'ASSIGN'
PLUS = '+'
MINUS = '-'
MULTIPLY = '*'
DIVIDE = '/'
REMAINDER = '%'
BOOLAND = '&'
BOOLOR = '|'
PREINC = 'PREINC'
POSTINC = 'POSTINC'
BOOLXOR = '^'
SHIFTL = '<<'
SHIFTR = '>>'
IF = 'IF'
IFNOT = 'IFNOT'
WHILE='WHILE'
FOR='FOR'
EQ = '=='
NEQ = '!='
GR = '>'
GE = '>='
VAR = 'VAR'
LIT = 'LIT'
STRING = 'STRING'
GOTO = 'GOTO'
LABEL = 'LABEL'
ADDR = 'ADDR'
DEREF = 'DEREF'
PRINT = 'PRINT'
PUTCHAR = 'PUTCHAR'
RETURN = 'RETURN'
MOV = 'MOV'

# We'll prefix this for our IR of the C code.
IR='IR_'
